In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [2]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [3]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [5]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [6]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [7]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [8]:
B = np.array([7, 8])
B.shape

(2,)

In [9]:
np.dot(A, B)

array([23, 53, 83])